Qrcode
Freemindtronic/evicypher-webmail pull request #18
Opened 2021-09-16 14:11 UTC by DylanDaCosta23

- **QRCode Button Implementation**
![QRCodeButton](https://user-images.githubusercontent.com/82520377/133627340-b5e8daff-dafd-47df-8b26-e9f63104b6cd.png)

- **QRCode Button Test**
![QRCodeTest](https://user-images.githubusercontent.com/82520377/133627485-ab3f44fc-473d-4fdf-88f5-2f6e19c3c642.png)

- **QRCode Limit Exceeded**
![LimitExceeded](https://user-images.githubusercontent.com/82520377/133627560-e930a9a0-7818-4cce-9873-65fa6a9699d3.png)

2021-09-16 15:50 UTC, zephvr requested changes
Il y a plusieurs points à revoir. J'ai commenté les lignes en question

2021-09-16 15:50 UTC, zephvr commented on src/content-scripts/common.ts
> +      const elemento: HTMLIFrameElement = document.querySelector('#iframeid')!
Également pas besoin de faire ce magouillage avec eslint réutilise juste la constante `frame`

2021-09-16 15:50 UTC, zephvr commented on src/content-scripts/common.ts
> +      const FrameHeightWidht = Number.parseInt(height!, 10) + 20
Fais le moins possible de bidouillage avec eslint

2021-09-17 12:39 UTC, DylanDaCosta23 commented on static/locales/fr/strings.json
> +  "are-you-sure": "Es-tu sûr?",
J'ai traduis avec i18n Ally. 
On peut laisser l'ancienne traduction si tu préfères.

2021-09-17 13:29 UTC, zephvr commented on static/locales/fr/strings.json
> +  "are-you-sure": "Es-tu sûr?",
Oui l'ancienne est mieux

2021-09-17 13:33 UTC, zephvr approved these changes
Tous les changements sont bon. 
Ok pour merge

2021-09-17 13:38 UTC, merged